linters:
  enable:
    # Default linters, plus these:
    - exportloopref
    - gocognit
    - goconst
    - gocritic
    - gofmt
    - gosec
    - misspell
    - revive

run:
  build-tags:
    - js,wasm

issues:
  exclude:
    # Disable scopelint errors on table driven tests
    - Using the variable on range scope `tc` in function literal
  include:
    # Re-enable default excluded rules
    - EXC0012
    - EXC0013
    - EXC0014
    - EXC0015
